// Code generated by swaggo/swag. DO NOT EDIT.

package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/costs/clusters/{cluster_id}/namespace": {
            "get": {
                "description": "Get specific cluster namespace costs with time range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Costs"
                ],
                "summary": "Get specific cluster namespace costs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster Id",
                        "name": "cluster_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "The start time to query",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The end time to query",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The step seconds of the data to return",
                        "name": "stepSeconds",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterNamespaceCostList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.StatusError"
                        }
                    }
                }
            }
        },
        "/costs/clusters/{cluster_id}/resource": {
            "get": {
                "description": "Get detailed information on cluster resource costs, including CPU, memory, and different billing modes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Costs"
                ],
                "summary": "Get detailed information on cluster resource costs, including CPU, memory, and different billing modes.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster Id",
                        "name": "cluster_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "The start time to query",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The end time to query",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The step seconds of the data to return",
                        "name": "stepSeconds",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterResourceCostList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.StatusError"
                        }
                    }
                }
            }
        },
        "/costs/clusters/{cluster_id}/summary": {
            "get": {
                "description": "Get specific cluster costs summary in current two month",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Costs"
                ],
                "summary": "Get specific cluster costs summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster Id",
                        "name": "cluster_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterCostsSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.StatusError"
                        }
                    }
                }
            }
        },
        "/costs/clusters/{cluster_id}/workload": {
            "get": {
                "description": "Get specific cluster workloads costs with time range",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Costs"
                ],
                "summary": "Get specific cluster workloads costs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster Id",
                        "name": "cluster_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "The start time to query",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The end time to query",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The step seconds of the data to return",
                        "name": "stepSeconds",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "The aggregated way to show workload costs",
                        "name": "aggregateBy",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterWorkloadCostList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.StatusError"
                        }
                    }
                }
            }
        },
        "/costs/summary": {
            "get": {
                "description": "Get all clusters costs summary in current two month",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Costs"
                ],
                "summary": "Get all clusters costs summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterCostsSummaryList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.StatusError"
                        }
                    }
                }
            }
        },
        "/metrics/clusters/{cluster_id}/cpu": {
            "get": {
                "description": "Get specific cluster CPU metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get specific cluster CPU metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster Id",
                        "name": "cluster_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "The start time to query",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The end time to query",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The step seconds of the data to return",
                        "name": "stepSeconds",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterResourceMetrics"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.StatusError"
                        }
                    }
                }
            }
        },
        "/metrics/clusters/{cluster_id}/memory": {
            "get": {
                "description": "Get specific cluster memory metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get specific cluster memory metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster Id",
                        "name": "cluster_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "The start time to query",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The end time to query",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "The step seconds of the data to return",
                        "name": "stepSeconds",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterResourceMetrics"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.StatusError"
                        }
                    }
                }
            }
        },
        "/metrics/clusters/{cluster_id}/summary": {
            "get": {
                "description": "Get specific cluster metrics summary in current two month",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get specific cluster metrics summary",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Cluster Id",
                        "name": "cluster_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterMetricsSummary"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.StatusError"
                        }
                    }
                }
            }
        },
        "/metrics/summary": {
            "get": {
                "description": "Get all clusters metrics summary in current two month",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Metrics"
                ],
                "summary": "Get all clusters metrics summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterMetricsSummaryList"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.StatusError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_kubefin_kubefin_pkg_api.ClusterCostsSummary": {
            "type": "object",
            "properties": {
                "ClusterAvgHourlyCoreCost": {
                    "description": "ClusterAvgDailyCost means average core/hour costs in current month",
                    "type": "number"
                },
                "cloudProvider": {
                    "type": "string"
                },
                "clusterActiveTime": {
                    "description": "ClusterActiveTime shows the cluster active time in seconds",
                    "type": "number"
                },
                "clusterAvgDailyCost": {
                    "description": "ClusterAvgDailyCost means average daily costs in current month",
                    "type": "number"
                },
                "clusterConnectionSate": {
                    "description": "ClusterConnectionSate can be running/connect_failed",
                    "type": "string"
                },
                "clusterId": {
                    "type": "string"
                },
                "clusterMonthCostCurrent": {
                    "description": "ClusterMonthCostCurrent means the total cost in current month",
                    "type": "number"
                },
                "clusterMonthEstimateCost": {
                    "description": "ClusterMonthEstimateCost means the estimating cost with previous 7 days costs",
                    "type": "number"
                },
                "clusterName": {
                    "type": "string"
                },
                "clusterRegion": {
                    "type": "string"
                },
                "connectionTime": {
                    "description": "ConnectionTime shows the time the cluster connected",
                    "type": "integer"
                },
                "lastActiveTime": {
                    "type": "integer"
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterCostsSummaryList": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterCostsSummary"
                    }
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterMetricsSummary": {
            "type": "object",
            "properties": {
                "cloudProvider": {
                    "type": "string"
                },
                "clusterActiveTime": {
                    "description": "ClusterActiveTime shows the cluster active time in seconds",
                    "type": "number"
                },
                "clusterConnectionSate": {
                    "description": "ClusterConnectionSate can be running/connect_failed",
                    "type": "string"
                },
                "clusterId": {
                    "type": "string"
                },
                "clusterName": {
                    "type": "string"
                },
                "clusterRegion": {
                    "type": "string"
                },
                "connectionTime": {
                    "description": "ConnectionTime shows the time the cluster connected",
                    "type": "integer"
                },
                "cpuCoreCapacity": {
                    "description": "CPUCoreCapacity means all nodes' cpu core capacity",
                    "type": "number"
                },
                "cpuCoreRequest": {
                    "description": "CPUCoreRequest means all pods' cpu core request",
                    "type": "number"
                },
                "cpuCoreTotal": {
                    "description": "CPUCoreTotal means all nodes' cpu core",
                    "type": "number"
                },
                "cpuCoreUsage": {
                    "description": "CPUCoreUsage means all pods' cpu core usage",
                    "type": "number"
                },
                "fallbackBillingNodeNumbersCurrent": {
                    "type": "integer"
                },
                "lastActiveTime": {
                    "type": "integer"
                },
                "nodeNumbersCurrent": {
                    "type": "integer"
                },
                "onDemandBillingNodeNumbersCurrent": {
                    "type": "integer"
                },
                "periodBillingNodeNumbersCurrent": {
                    "type": "integer"
                },
                "podScheduledCurrent": {
                    "type": "integer"
                },
                "podTotalCurrent": {
                    "type": "integer"
                },
                "podUnscheduledCurrent": {
                    "type": "integer"
                },
                "ramGBCapacity": {
                    "description": "RAMGBCapacity means all nodes' ram gb capacity",
                    "type": "number"
                },
                "ramGBRequest": {
                    "description": "RAMGBRequest all pods' ram gb request",
                    "type": "number"
                },
                "ramGBTotal": {
                    "description": "RAMGBTotal means all nodes' ram gb",
                    "type": "number"
                },
                "ramGBUsage": {
                    "description": "RAMGBUsage means all pods' ram gb usage",
                    "type": "number"
                },
                "spotBillingNodeNumbersCurrent": {
                    "type": "integer"
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterMetricsSummaryList": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterMetricsSummary"
                    }
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterNamespaceCost": {
            "type": "object",
            "properties": {
                "costList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterNamespaceCostDetail"
                    }
                },
                "namespace": {
                    "type": "string"
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterNamespaceCostDetail": {
            "type": "object",
            "properties": {
                "cpuCoreUsage": {
                    "type": "number"
                },
                "cpuRequest": {
                    "type": "number"
                },
                "podCount": {
                    "description": "PodCount means the average pod count in this period",
                    "type": "number"
                },
                "ramGBRequest": {
                    "type": "number"
                },
                "ramGBUsage": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                },
                "totalCost": {
                    "type": "number"
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterNamespaceCostList": {
            "type": "object",
            "properties": {
                "clusterId": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterNamespaceCost"
                    }
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterResourceCost": {
            "type": "object",
            "properties": {
                "costFallbackBillingMode": {
                    "description": "TODO: implement this type",
                    "type": "number"
                },
                "costOnDemandBillingMode": {
                    "type": "number"
                },
                "costPeriodBillingMode": {
                    "type": "number"
                },
                "costSpotBillingMode": {
                    "type": "number"
                },
                "cpuCoreCount": {
                    "description": "CPUCoreCount means the average core hour count in this period",
                    "type": "number"
                },
                "cpuCoreUsage": {
                    "description": "CPUCoreUsage means the average core hour usage in this period",
                    "type": "number"
                },
                "cpuCost": {
                    "type": "number"
                },
                "ramCost": {
                    "type": "number"
                },
                "ramGBCount": {
                    "description": "RAMGBCount means the average ram hour count in this period",
                    "type": "number"
                },
                "ramGBUsage": {
                    "description": "RAMGBUsage means the average ram hour usage in this period",
                    "type": "number"
                },
                "timestamp": {
                    "description": "Timestamp is in unix timestamp format, you can transform it to any you want",
                    "type": "integer"
                },
                "totalCost": {
                    "type": "number"
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterResourceCostList": {
            "type": "object",
            "properties": {
                "clusterId": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterResourceCost"
                    }
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterResourceMetrics": {
            "type": "object",
            "properties": {
                "clusterId": {
                    "type": "string"
                },
                "resourceAllocatableValues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SamplePair"
                    }
                },
                "resourceCapacityValues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SamplePair"
                    }
                },
                "resourceRequestValues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SamplePair"
                    }
                },
                "resourceTotalValues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SamplePair"
                    }
                },
                "resourceType": {
                    "type": "string"
                },
                "resourceUsageValues": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.SamplePair"
                    }
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterWorkloadCost": {
            "type": "object",
            "properties": {
                "costList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterWorkloadCostDetail"
                    }
                },
                "namespace": {
                    "type": "string"
                },
                "workloadName": {
                    "type": "string"
                },
                "workloadType": {
                    "description": "WorkloadType could be pod/daemonset/statefulset/deployment",
                    "type": "string"
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterWorkloadCostDetail": {
            "type": "object",
            "properties": {
                "cpuCoreRequest": {
                    "type": "number"
                },
                "cpuCoreUsage": {
                    "type": "number"
                },
                "podCount": {
                    "description": "PodCount means the average pod count in this period",
                    "type": "number"
                },
                "ramGBRequest": {
                    "type": "number"
                },
                "ramGBUsage": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                },
                "totalCost": {
                    "type": "number"
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.ClusterWorkloadCostList": {
            "type": "object",
            "properties": {
                "clusterId": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_kubefin_kubefin_pkg_api.ClusterWorkloadCost"
                    }
                }
            }
        },
        "github_com_kubefin_kubefin_pkg_api.StatusError": {
            "type": "object",
            "properties": {
                "apiVersion": {
                    "type": "string"
                },
                "code": {
                    "type": "integer"
                },
                "kind": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "model.SamplePair": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "KubeFin API",
	Description:      "KubeFin Cost Analyzer API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
