# Copyright 2022 The KubeFin Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: KubeFin e2e

on:
  pull_request:
    branches: [ 'main', 'release-*' ]

env:
  KIND_VERSION: 0.17.0
  GOTESTSUM_VERSION: 1.7.0
  KO_FLAGS: --platform=linux/amd64

jobs:
  e2e-test:
    runs-on: kubefin-e2e-env
    strategy:
      fail-fast: true
      matrix:
        k8s-version:
          - v1.27.3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker
      uses: crazy-max/ghaction-setup-docker@v2

    - name: Set up Go 1.20.x
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.x

    - uses: kubefin/actions/composite/setup-ko@main

    - uses: kubefin/actions/composite/setup-gotestsum@main
      with:
        version: ${GOTESTSUM_VERSION}

    - uses: kubefin/actions/composite/setup-kind@main
      with:
        version: ${KIND_VERSION}

    - name: Launch KubeFin with kind cluster
      run: |
        set -x

        export K8S_VERSION=${{ matrix.k8s-version }}
        hack/local-start-kubefin.sh

    - name: Set kubeconfig path
      if: ${{ failure() }}
      run: |
        kind export kubeconfig --name kubefin-server

    - uses: chainguard-dev/actions/kind-diag@main
      # Only upload logs on failure.
      if: ${{ failure() }}
      with:
        cluster-resources: nodes,namespaces
        namespace-resources: pods,svc,deployment,statefulset
        artifact-name: logs-${{ matrix.k8s-version }}
